version: '3'

services:

  proxy:
    image: vfarcic/docker-flow-proxy:latest

    ports:
      - 80:80
      - 443:443
      - 8080:8080
    networks:
      - balancers-network
    environment:
      - MODE=swarm
      - LISTENER_ADDRESS=swarm-listener
      - CONNECTION_MODE=http-server-close

  swarm-listener:
    image: vfarcic/docker-flow-swarm-listener:latest
    networks:
      - balancers-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DF_NOTIFY_CREATE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/reconfigure
      - DF_NOTIFY_REMOVE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/remove
    deploy:
      placement:
        constraints: [node.role == manager]
  
  proxy-blue:
    image: vfarcic/docker-flow-proxy:latest

    ports:
      - 81:80
      - 444:443
      - 8081:8080
    networks:
      - balancers-network
    environment:
      - MODE=swarm
      - LISTENER_ADDRESS=swarm-listener
      - CONNECTION_MODE=http-server-close

  cluster-blue:
    image: marcsolde/demo-app:v1
    ports:
      - 3000:3000
    networks:
      - balancers-network
      - internal-network
    deploy:
      replicas: 3
    environment:
      - DOCKER_SERVICE_NAME=blue
  
  proxy-green:
    image: vfarcic/docker-flow-proxy:latest

    ports:
      - 82:80
      - 445:443
      - 8082:8080
    networks:
      - balancers-network
    environment:
      - MODE=swarm
      - LISTENER_ADDRESS=swarm-listener
      - CONNECTION_MODE=http-server-close
  
  console:
    image: marcsolde/webconsolebgdemo:latest
    ports: 
      - 8000:8000
    networks:
      - balancers-network
      - internal-network


networks:
  balancers-network:
    external: true
  internal-network:
    external: true
